### ISSUE TITLE
Keeping them updated

### ISSUE THREAD

**Issue by KrishnaPG** [justinmc/meteor-backbone-boilerplate#1]
Was trying to use `backbone` for my app - but the problem is this picks up `backbone` from atmosphere which may or may not be updated to the latest version. So, we are at the mercy of the guy whoever is providing that atmoshphere `backbone` package.

In my case, I had to waste halfday debugging a problem - just to realize that the version of `backbone` provided by atmosphere is old one. 

How to overcome this issue? How to depend on directly the CDN and not these atmosphere old versions?

**Comment by justinmc** [comment]
Sorry for the late reply.  You can solve this by downloading the latest version of Backbone and placing in `client/lib/` (Meteor loads these scripts first).  Also uninstall the atmosphere version of Meteor with `meteor uninstall backbone`.

As for this project itself, it's probably best to use the atmosphere version to keep things (mostly) up to date and to not add Backbone to the repo.  People who need a specific version can follow the steps above.

Closing for now, but let me know if this works for you!
